import React from 'react'
import Head from 'next/head'

import IndexNavbar from '../Navbars/indexNavbar'
import Footer from '../Footers/footer'

const Layout = ({ children }) => {
    return (
    <>
        <Head>
            <title>EA SPORTS™ FIFA Online 4 เกมฟุตบอลออนไลน์ เล่นฟรี</title>
            <meta property="description" content="FIFA Online 4 :เกมฟุตบอลออนไลน์ระดับโลก พร้อมให้คุณสัมผัสประสบการณ์ที่สมจริง กับการสร้างทีมในฝันจากนักเตะที่ชื่นชอบ อ้างอิงจากฟุตบอลจริง ด้วยนักเตะกว่า 10,000 คน จากลีกชั้นนำทั่วโลก" class="next-head"></meta>
            <meta property="keyword" content="เกม,เกมส์,ฟุตบอล,บอล,เกมฟุตบอล,เกมบอล,เกมส์บอล,เกมบอลใหม่,เกมส์ฟุตบอล,เกมฟุตบอลออนไลน์,เกมส์ฟุตบอลออนไลน์,เกมฟุตบอลใหม่,เกมส์ฟุตบอลใหม่,เกมใหม่,เกมส์ใหม่,เกมออนไลน์,เกมส์ออนไลน์,เกมน่าเล่น,เกมส์น่าเล่น,เกมส์หน้าเล่น,เกมหน้าเล่น,โหลดเกมส์,โหลดเกม,เว็บฟีฟ่า,เกมบอล2018,เกมบอล2019 เกมส์บอล2018,เกมส์บอล2019,บอลฟีฟ่า,เกมบอลมือถือ,ฟีฟ่าออนไลน์,ฟีฟ่า,ฟีฟ่า4,เตะฟุตบอล,ฟีฟ่ามือถือ, ฟีฟ่าโบบาย,FOM,FIFA Online 4 ,FIFA,game,gamefootball,gamefootballonline,game2018,gamefootballonline2018, gameball" class="next-head"></meta>
            <meta property="og:title" content="EA SPORTS™ FIFA Online 4 เกมฟุตบอลออนไลน์ เล่นฟรี" class="next-head"></meta>
            <meta property="og:description" content="FIFA Online 4 :เกมฟุตบอลออนไลน์ระดับโลก พร้อมให้คุณสัมผัสประสบการณ์ที่สมจริง กับการสร้างทีมในฝันจากนักเตะที่ชื่นชอบ อ้างอิงจากฟุตบอลจริง ด้วยนักเตะกว่า 10,000 คน จากลีกชั้นนำทั่วโลก" class="next-head"></meta>
            <meta property="og:type" content="website" class="next-head"></meta>
            <meta property="og:image" content="https://cdngarenanow-a.akamaihd.net/webth/cdn/fo4/reskin/share.jpg" class="next-head"></meta>
            <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=0"></meta>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />

            <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"/>
            <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"/>
        </Head>
        <body>
            <IndexNavbar />
            <main className="main-content">
                {children}
            </main>
            <Footer />
        </body>
    </>
    )
}

export default Layout;